# Generated by Django 3.1.6 on 2021-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='read',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='readtext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
    ]
