# Generated by Django 3.1.6 on 2021-02-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0002_auto_20210203_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatmodel',
            name='subtitle',
            field=models.TextField(blank=True, default='a', null=True),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
