# Generated by Django 3.1.7 on 2021-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0004_eatmodel_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatmodel',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='snsimage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
